apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdscloud-cloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLables:
      app: cdscloud-cloud-controller-manager
  template:
    metadata:
      labels:
        app: cdscloud-cloud-controller-manager
    spec:
      dnsPolicy: Default
      serviceAccountName: cloud-controller-manager
      tolerations:
      - key: "node.cloudprovider.kubernetes.io/uninitialized"
        value: "true"
        effect: "NoSchedule"
      - key: "node.kubernetes.io/network-unavailable"
        value: "true"
        effect: "NoSchedule"
      containers:
      - image: registry-bj.capitalonline.net/cck/cdscloud-controller-manager:test1
        name: cdscloud-cloud-controller-manager
        command:
        - --cloud-provider=cdscloud # 指定 cloud provider 为 cdscloud
