kind: Service
apiVersion: v1
metadata:
  name: lb-tcp
  annotations:
    service.beta.kubernetes.io/cds-load-balancer-protocol: http | tcp
    service.beta.kubernetes.io/cds-load-balancer-size:  large | normal | medium | small
    service.beta.kubernetes.io/cds-load-balancer-max-connection: max | medium | min
#    service.beta.kubernetes.io/healthy-check: true | false
#    service.beta.kubernetes.io/timeout: 10s | 20s | 30s
spec:
  type: LoadBalancer
  selector:
    app: ccm-nginx-example
  ports:
  - name: ccm-tcp
    protocol: TCP
    port: 80
    targetPort: 80