kind: Service
apiVersion: v1
metadata:
  name: lb-tcp
  namespace: default
  annotations:
    service.beta.kubernetes.io/cds-load-balancer-protocol: http
    service.beta.kubernetes.io/cds-load-balancer-size:  large
    service.beta.kubernetes.io/cds-load-balancer-max-connection: 20000
spec:
  type: LoadBalancer
  selector:
    app: ccm-nginx-example
  ports:
  - name: ccm-tcp
    protocol: TCP
    port: 80
    targetPort: 80